name: scale_ui_v3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  flutter_libserialport: ^0.4.0
  intl: ^0.19.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/OK.mp3
    - assets/NG.mp3